### ISSUE TITLE
Remove unncessary attempt to install cl-lib

### ISSUE THREAD

**Issue by progfolio** [algon-ns/nec.emacs.d#1]
Unless you are using Emacs verison < 24.3 (doubtful), cl-lib is installed by default with your Emacs.
Thus, this call is unnecessary:

 https://github.com/algon-ns/nec.emacs.d/blob/3a4a1f6645979065646e6591c02cbaa07dadd0d5/init.el#L84

**Comment by algon-ns** [comment]
has been deleted
