### ISSUE TITLE
Org-version depends on full repo clone

### ISSUE THREAD

**Issue by progfolio** [algon-ns/nec.emacs.d#2]
Since you have `straight-vc-git-default-clone-depth` set to `1`, your Org repo is a shallow clone, which will not properly generate `org-version`. This can be corrected by adding the `:depth` keyword to your recipe for Org:

```emacs-lisp
(straight-use-package '(org-plus-contrib :depth full))
```

**Comment by algon-ns** [comment]
I've tried any combination (obviously except the rigth one), and the error is still there:
 _Org-mode fatal: No names found, cannot describe anything._
I've removed the straight-vc-git-default-clone-depth statement, with no luck.
I'm really in doubt on the diffence between org-plus-contrib and org-contrib
git is updated to the current (wrong) version

**Comment by algon-ns** [comment]
This morning org 9.4.4 came up....
I did not change anything, but now it works
